.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/release_template.md, .github/workflows/maven-test-pr.yml, README.md, src/.gitignore, src/jag-vips-client/pom.xml, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/AutoConfiguration.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/VipsClientProperties.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/VipsOrdsClientConstants.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/document/DocumentService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/document/DocumentServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/document/VipsDocumentResponse.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/health/HealthResponse.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/health/HealthService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/health/HealthServiceImpl.java, src/jag-vips-client/src/main/resources/META-INF/spring.factories, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/document/DocumentServiceImplTest.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/health/HealthServiceImplTest.java, src/jag-vips-client/vipsords.yaml, src/pom.xml
- Adding library from DPS
if your change is a breaking change, please add `breaking change` label to this PR
Not TESTED
=> Moving ORDS vips libs

src/jag-vips-client/pom.xml, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionStatus.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/VipsProhibitionStatusResponse.java, src/jag-vips-client/vipsords.yaml, src/pom.xml
Changes to support the VIPS ORDS Get Prohibition Status operation.
=> digitalfrms_DF-182_1

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/AutoConfiguration.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/VipsProhibitionStatusResponse.java, src/jag-vips-client/vipsords.yaml
- Added prohib status bean to autoconfig. 
- Changed response code/message attribute names.
=> digitalfrms_DF-182_2

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/PaymentService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/PaymentServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/PaymentStatus.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/VipsPaymentStatusResponse.java, src/jag-vips-client/vipsords.yaml
Added payment status service stubs
DF-185
Type of change
[ ] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality)
[ ] Refactoring / Documentation
if your change is a breaking change, please add breaking change label to this PR
How Has This Been Tested?
Untested stubs
Checklist:
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[ ] I have made corresponding changes to the documentation
[x] New and existing unit tests pass locally with my changes
=> Added payment status service stubs

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/PaymentService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/PaymentServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/VipsPaymentResponse.java, src/jag-vips-client/vipsords.yaml
DF 189
Type of change
[ ]  Bug fix (non-breaking change which fixes an issue)
[x]  New feature (non-breaking change which adds functionality)
[ ]  Refactoring / Documentation
if your change is a breaking change, please add breaking change label to this PR
How Has This Been Tested?
Please describe the tests that you ran to verify your changes.
Untested stubs
Checklist:
[x]  My code follows the style guidelines of this project
[x]  I have performed a self-review of my own code
[ ]  I have made corresponding changes to the documentation
[x]  New and existing unit tests pass locally with my changes
=> Added stubs for post payment details

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/payment/VipsPaymentResponse.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/payment/PaymentServiceImplTest.java
=> Added unit test stubs

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImpl.java
- DF-388
if your change is a breaking change, please add `breaking change` label to this PR
Please describe the tests that you ran to verify your changes.
Local test
=> Added logger statements and correlation id

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImpl.java
- DF-388
if your change is a breaking change, please add `breaking change` label to this PR
Please describe the tests that you ran to verify your changes.
Local test
=> Removed correlationId duplicate logging

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/VipsProhibitionStatusResponse.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImplTest.java
DF-407 - Added prohibition service unit tests
=> Added prohibition service unit tests

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/AutoConfiguration.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureResponse.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DocumentInfo.java, src/jag-vips-client/vipsords.yaml
DF-296, DF-366 - Added disclosure service stubs
=> Added disclosure service stubs

src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImplTest.java
=> Added unit tests stubs

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImpl.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImplTest.java
=> Updated disclosure service get

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImpl.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImplTest.java
=> Added dummy disclosure stubs

src/jag-vips-client/pom.xml, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureService.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImpl.java, src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionStatus.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImplTest.java, src/jag-vips-client/vipsords.yaml
DF-495, DF-455
Log statements of Disclosure service:
DisclosureServiceImpl        : Processed Get Disclosure Document request: ORDS returned file: download-3399954761418913121 
DisclosureServiceImpl        : Disclosure Service could not find document: Record not found 
DisclosureServiceImpl        : Disclosure Service could not find document: ORA-01422: exact fetch returns more than requested number of rows 
Application Id:
=> Updated disclosure service get, added application id to prohibition status

.gitignore, README.md, src/jag-vips-client/pom.xml, src/pom.xml
- update version to 0.1.0
if your change is a breaking change, please add `breaking change` label to this PR
Please describe the tests that you ran to verify your changes.
=> update version to 0.1.0

src/jag-vips-client/pom.xml
https://justice.gov.bc.ca/jira/browse/RDFP-68 - RSBC VIPS Java 17 Upgrade
=> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement

src/jag-vips-client/pom.xml, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/disclosure/DisclosureServiceImplTest.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/document/DocumentServiceImplTest.java, src/jag-vips-client/src/test/java/ca/bc/gov/open/jagvipsclient/prohibition/ProhibitionServiceImplTest.java, src/jag-vips-client/vipsords.yaml
=> remove jersey2 from openapi-generator-maven-plugin

src/jag-vips-client/pom.xml
=> remove nexus

src/jag-vips-client/pom.xml
=> spring boot starter parent update

src/jag-vips-client/pom.xml
=> Vulnerabilities

src/jag-vips-client/src/main/java/ca/bc/gov/open/jagvipsclient/VipsClientAutoConfiguration.java
Added Validation Api/Service to VipsClientAutoConfiguration
=> Added Validation Beans
